# Generated by Django 4.2 on 2023-07-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conditions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='条件名')),
                ('desc', models.CharField(max_length=256, verbose_name='条件描述')),
                ('condtype', models.CharField(max_length=16, verbose_name='类型')),
                ('operatorid', models.IntegerField(verbose_name='所用运算符')),
                ('argvs', models.CharField(max_length=256, verbose_name='参数集合')),
                ('creatorid', models.CharField(max_length=32, verbose_name='用户id')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='创建时间')),
                ('changetime', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '条件表',
                'verbose_name_plural': '条件表',
                'db_table': 'conditonpool',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='monitortask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='任务名')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='任务描述')),
                ('tasktype', models.CharField(blank=True, max_length=16, verbose_name='任务类型')),
                ('strategyid', models.IntegerField(blank=True, verbose_name='策略id')),
                ('stockpoolid', models.IntegerField(blank=True, verbose_name='股票池id')),
                ('creatorid', models.CharField(blank=True, max_length=32, verbose_name='所属用户id')),
                ('lastrun', models.CharField(blank=True, max_length=20, verbose_name='最后运行时间')),
                ('runstatus', models.CharField(blank=True, max_length=16, verbose_name='运行状态')),
                ('noticeid', models.IntegerField(blank=True, verbose_name='通知配置方案id')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '监控任务',
                'verbose_name_plural': '监控任务',
                'db_table': 'monitortask',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='noticeconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creatorid', models.CharField(blank=True, max_length=32, verbose_name='所属用户id')),
                ('method', models.CharField(blank=True, max_length=32, verbose_name='通知方案')),
                ('email', models.CharField(blank=True, max_length=32, verbose_name='email')),
                ('phonenum', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='创建时间')),
                ('changetime', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '通知方案配置',
                'verbose_name_plural': '通知方案配置',
                'db_table': 'noticeconfig',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='operators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='运算符')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='运算符描述')),
                ('oprtype', models.CharField(max_length=16, verbose_name='运算符类型')),
                ('argvnum', models.IntegerField(verbose_name='参数数量')),
                ('creatorid', models.CharField(blank=True, max_length=32, verbose_name='用户id')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='创建时间')),
                ('changetime', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '运算符表',
                'verbose_name_plural': '运算符表',
                'db_table': 'operatorpool',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='stockbasicinfo',
            fields=[
                ('stockcode', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='股票id')),
                ('stockname', models.CharField(max_length=32, verbose_name='股票名称')),
            ],
            options={
                'verbose_name': '股票基础信息',
                'verbose_name_plural': '股票基础信息',
                'db_table': 'stockbasicinfo',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='stockpool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='股票池名称')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='股票池描述')),
                ('stockpooltype', models.CharField(blank=True, max_length=16, verbose_name='股票池类型')),
                ('creatorid', models.CharField(blank=True, max_length=32, verbose_name='所属用户id')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='创建时间')),
                ('changetime', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '股票池',
                'verbose_name_plural': '股票池',
                'db_table': 'stockpool',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='strategyorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategyid', models.IntegerField(blank=True, verbose_name='策略id')),
                ('buyerid', models.CharField(blank=True, max_length=32, verbose_name='买方id')),
                ('sellerid', models.CharField(blank=True, max_length=32, verbose_name='卖方id')),
            ],
            options={
                'verbose_name': '策略模型交易订单',
                'verbose_name_plural': '策略模型交易订单',
                'db_table': 'strategyorder',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='strategys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=16, verbose_name='策略名')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='策略描述')),
                ('sttype', models.CharField(blank=True, max_length=16, verbose_name='策略类型')),
                ('expression', models.CharField(blank=True, max_length=256, verbose_name='策略表达式')),
                ('ownderid', models.CharField(blank=True, max_length=32, verbose_name='拥有者id')),
                ('creatorid', models.CharField(blank=True, max_length=32, verbose_name='创建者id')),
                ('createtime', models.CharField(blank=True, max_length=20, verbose_name='创建时间')),
                ('owntime', models.CharField(blank=True, max_length=20, verbose_name='归属时间')),
                ('changetime', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('validtime', models.CharField(blank=True, max_length=20, verbose_name='有效期')),
                ('runstatus', models.CharField(blank=True, max_length=16, verbose_name='策略运行状态')),
                ('buyoutprice', models.IntegerField(blank=True, verbose_name='买断售价')),
                ('unitprice', models.IntegerField(blank=True, verbose_name='购买时间单价')),
                ('protectlevel', models.IntegerField(blank=True, verbose_name='策略保护级别')),
                ('linkid', models.IntegerField(blank=True, verbose_name='绑定到某个策略')),
                ('popular', models.IntegerField(blank=True, verbose_name='策略点赞热度')),
            ],
            options={
                'verbose_name': '用户策略',
                'verbose_name_plural': '用户策略',
                'db_table': 'strategypool',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='strategyyields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategyid', models.IntegerField(blank=True, verbose_name='策略id')),
                ('stockpoolid', models.IntegerField(blank=True, verbose_name='绑定股票池id')),
                ('yields', models.DecimalField(blank=True, decimal_places=4, max_digits=7, verbose_name='收益率')),
                ('starttime', models.CharField(blank=True, max_length=20, verbose_name='起始时间')),
                ('endtime', models.CharField(blank=True, max_length=20, verbose_name='终止时间')),
            ],
            options={
                'verbose_name': '策略收益',
                'verbose_name_plural': '策略收益',
                'db_table': 'strategyyields',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='usermanager',
            fields=[
                ('userid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户id')),
                ('useraccount', models.CharField(blank=True, max_length=32, verbose_name='微信的账号用户名')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='微信昵称')),
                ('registtime', models.CharField(blank=True, max_length=20, verbose_name='注册时间')),
                ('uuid', models.CharField(blank=True, max_length=32, verbose_name='用户标识')),
                ('level', models.CharField(blank=True, max_length=8, verbose_name='用户等级')),
                ('valid', models.BooleanField(blank=True, verbose_name='生效状态')),
                ('validtime', models.CharField(blank=True, max_length=20, verbose_name='截止有效时间')),
                ('cashflow', models.IntegerField(blank=True, verbose_name='流水')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'usermanager',
                'abstract': False,
            },
        ),
    ]
