# Generated by Django 4.2 on 2023-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategys',
            name='buyoutprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='买断售价'),
        ),
    ]
