# Generated by Django 4.2 on 2023-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeconfig',
            name='email',
            field=models.CharField(blank=True, max_length=32, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='noticeconfig',
            name='phonenum',
            field=models.CharField(blank=True, max_length=32, verbose_name='手机号'),
        ),
    ]
