# Generated by Django 4.2 on 2023-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_noticeconfig_email_noticeconfig_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeconfig',
            name='changetime',
            field=models.DateTimeField(auto_now=True, verbose_name='变更时间'),
        ),
        migrations.AddField(
            model_name='noticeconfig',
            name='createtime',
            field=models.CharField(blank=True, max_length=20, verbose_name='创建时间'),
        ),
    ]
