# Generated by Django 4.2 on 2023-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_alter_strategys_buyoutprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortask',
            name='noticeid',
            field=models.IntegerField(blank=True, null=True, verbose_name='通知配置方案id'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='stockpoolid',
            field=models.IntegerField(blank=True, null=True, verbose_name='股票池id'),
        ),
        migrations.AlterField(
            model_name='monitortask',
            name='strategyid',
            field=models.IntegerField(blank=True, null=True, verbose_name='策略id'),
        ),
        migrations.AlterField(
            model_name='strategyorder',
            name='strategyid',
            field=models.IntegerField(blank=True, null=True, verbose_name='策略id'),
        ),
        migrations.AlterField(
            model_name='strategys',
            name='linkid',
            field=models.IntegerField(blank=True, null=True, verbose_name='绑定到某个策略'),
        ),
        migrations.AlterField(
            model_name='strategys',
            name='popular',
            field=models.IntegerField(blank=True, null=True, verbose_name='策略点赞热度'),
        ),
        migrations.AlterField(
            model_name='strategys',
            name='protectlevel',
            field=models.IntegerField(blank=True, null=True, verbose_name='策略保护级别'),
        ),
        migrations.AlterField(
            model_name='strategys',
            name='unitprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='购买时间单价'),
        ),
        migrations.AlterField(
            model_name='strategyyields',
            name='stockpoolid',
            field=models.IntegerField(blank=True, null=True, verbose_name='绑定股票池id'),
        ),
        migrations.AlterField(
            model_name='strategyyields',
            name='strategyid',
            field=models.IntegerField(blank=True, null=True, verbose_name='策略id'),
        ),
    ]
