# Generated by Django 4.2 on 2023-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_alter_monitortask_noticeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeconfig',
            name='desc',
            field=models.CharField(blank=True, max_length=256, verbose_name='任务描述'),
        ),
        migrations.AddField(
            model_name='noticeconfig',
            name='name',
            field=models.CharField(blank=True, max_length=16, verbose_name='通知方案名'),
        ),
    ]
