# Generated by Django 4.2 on 2023-07-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0005_delete_operators_remove_conditions_argvs_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conditions',
            table='conditions',
        ),
        migrations.AlterModelTable(
            name='strategys',
            table='strategys',
        ),
    ]
