# Generated by Django 4.2 on 2023-05-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': '过滤器表', 'verbose_name_plural': '过滤器表'},
        ),
        migrations.AlterModelOptions(
            name='indicatorexpression',
            options={'verbose_name': '指标表达式', 'verbose_name_plural': '指标表达式'},
        ),
        migrations.AlterModelOptions(
            name='indicators',
            options={'verbose_name': '指标标准库', 'verbose_name_plural': '指标标准库'},
        ),
        migrations.AlterModelOptions(
            name='stockpool',
            options={'verbose_name': '股票池', 'verbose_name_plural': '股票池'},
        ),
        migrations.AlterModelOptions(
            name='strategyorder',
            options={'verbose_name': '策略模型交易订单', 'verbose_name_plural': '策略模型交易订单'},
        ),
        migrations.AlterModelOptions(
            name='strategypool',
            options={'verbose_name': '用户策略', 'verbose_name_plural': '用户策略'},
        ),
        migrations.AlterModelOptions(
            name='strategyyields',
            options={'verbose_name': '策略收益', 'verbose_name_plural': '策略收益'},
        ),
        migrations.AlterModelTable(
            name='filter',
            table='filter',
        ),
        migrations.AlterModelTable(
            name='indicatorexpression',
            table='indicatorexpression',
        ),
        migrations.AlterModelTable(
            name='indicators',
            table='indicators',
        ),
        migrations.AlterModelTable(
            name='stockpool',
            table='stockpool',
        ),
        migrations.AlterModelTable(
            name='strategyorder',
            table='strategyorder',
        ),
        migrations.AlterModelTable(
            name='strategypool',
            table='strategypool',
        ),
        migrations.AlterModelTable(
            name='strategyyields',
            table='strategyyields',
        ),
    ]
