# Generated by Django 4.2 on 2023-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_alter_filter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategypool',
            name='runstatus',
            field=models.CharField(max_length=16, verbose_name='策略运行状态'),
        ),
    ]
